### ISSUE TITLE
option-ext is MPL 2.0 licensed which is a copyleft dependency licence

### ISSUE THREAD

**Issue by trondhe** [dirs-dev/dirs-sys-rs#28]
Not sure how propagating licences work, but since dirs-rs depends on dirs-sys which depends on option-ext, which is using MPL 2.0 licensce. This cannot be used in closed source projects.
I sadly have no way around this and cannot open source what I use, so I cannot use dirs-rs due to this.

Afaik rust 1.76 has inspect on option types which can replace this dependency.

**Comment by trondhe** [comment]
Maybe a bit unfortunate writing on my part, but it was ment to be taken with the context of the first sentence which states im a bit unsure how this ends up working.

i.e. if you have a GPL3 based dependency, your library must also be GPL3 licensed. I might have misunderstood the MPL 2.0 license however, and that it acts more like any changes to itself must be published, while you can link into it without any problems.

**Comment by soc** [comment]
Closing this. Feel free to reopen if you have identified an issue.
